			<div id="featured" class="grid col-940">
				<div class="grid col-460">
					<h1 class="featured-title"></h1>
					<h2 class="featured-subtitle">What is MathsMix?</h2>
					<p>MathsMix is a companion program for maths classes at an early secondary level. We provide electronic worksheets to consolidate core skills, and challenge students to apply classroom concepts in problem-solving excercises.</p>

					<div class="call-to-action">

						<a href="#nogo" class="blue button">Sign Up</a>

					</div>
					<!-- end of .call-to-action -->


				</div>
				<!-- end of .col-460 -->

				<div id="featured-image" class="grid col-460 fit">

					<img class="aligncenter" src="img/Nuvola_apps_kfig.svg"
						alt="" height="300" width="260">

				</div>
				<!-- end of #featured-image -->

			</div>
			<!-- end of #featured -->


			<div id="widgets" class="home-widgets">
				<div class="grid col-300">

					<div class="widget-wrapper">

						<div class="widget-title-home">
							<h3>Students</h3>
						</div>
						<div class="textwidget">A small blurb about how MathsMix is good for a student.</div>

					</div>
					<!-- end of .widget-wrapper -->

				</div>
				<!-- end of .col-300 -->

				<div class="grid col-300">

					<div class="widget-wrapper">

						<div class="widget-title-home">
							<h3>Teachers</h3>
						</div>
						<div class="textwidget">A small blurb about how MathsMix is good for a teacher.</div>

					</div>
					<!-- end of .widget-wrapper -->

				</div>
				<!-- end of .col-300 -->

				<div class="grid col-300 fit">

					<div class="widget-wrapper">

						<div class="widget-title-home">
							<h3>Schools</h3>
						</div>
						<div class="textwidget">A small blurb about how MathsMix is good for a whole school.</div>

					</div>
					<!-- end of .widget-wrapper -->

				</div>
				<!-- end of .col-300 fit -->
			</div>
			<!-- end of #widgets -->
